<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGin9eyC\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGin9eyC/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGin9eyC.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGin9eyC\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerGin9eyC\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Gin9eyC',
    'container.build_id' => '58c835e0',
    'container.build_time' => 1532805484,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerGin9eyC');
